apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: peter-access
  namespace: mynamespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list","create"]
- apiGroups: ["","extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: peter-role-binding
  namespace: mynamespace
subjects:
- kind: User
  name: peter
  namespace: mynamespace
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: peter-access
  apiGroup: rbac.authorization.k8s.io