
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXdPREF3TlRFeE1Wb1hEVE15TURFd05qQXdOVEV4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFptCmN2Z2dzcDIyVGFENTFpMHhnYmhDTmYvbUV4ems5Z0pQcURxcVZsL2NyZ0lOMThIbk1YV3liYzFMY1JyeDd6ZzcKN0ZWaGhDWlJhdTdMakJpOHo2TUw2aGlGMU5JZUFkTVBRQmZad2lNYzlzekd2QXJrNG1wSXl0cHR4QW14MGg3Swp2YVdlRFg3NXY3bkl5TVVRU20vbXJjMzJIQlNDc3RzejBOTnVkanc0OWJpZVNTcGswSmlRREd4QWhIS1NjMXAzClIzNC9tSytXYTE2RmJuOVh6UlM0dWNGWHZNMHJwZUtBVVl1STJKTVQzNnA2NExRVnBaaUpwbzlnekFsaG1Sam4Kb3VqcmtWeEhRTjVlQ3BpVE1vNnl4Skc2SFNvTjIvSk41dHlacVZSbjU1clpoUFRYWkIvQWJYVU5GMC90MHhtUwp2VVA3K0NwODRHTnpsNEsvQ3NjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQL29wczNXNW5TUDZXQ3pIWnFLMkl6YmZqTXZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS3oxTFN3VVd1SE1sR29iVk1MYwpVem02czRXYWp2RCs0Ty9USERwcTJzcXo5VnB2ODErS2VpVFFkT3RDTUlhQWNnSjl6THZsVXFDZFNOV2lwZTl6CjZmMnRMcmNsNm9QOUZPRHhJdFB0YnN4K3RyMkNvalRSOXBHU0IxVnREa1ZjMlJ6YktQRzNMM0MxaGhCL2dWR0sKanNPcFRwR09SL2ZjbWRZQzdDRitVdEFoM0RTY2tzNmdNS2ZhL1N6ZGd1QkJDVXlUN01oRjFGc20vTFFPZ05XcApKT3ZVcC90bzNxd3BHUi9qSDM2RUtwUXRSQ2UyVTJHM25uNGR5NHRsbDFZdGMzL2JQZXF6ZkV6UlNQMUJRWEJ6Cld5ZGRDdUVJRWlYTXFjVVFxZkxnc2RXWTNrZnMvaitqdWcwYkpNa0xJaTdlZHVxZjhaMzR3c3ZKbkNzY1lIRWIKMWNzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://520de620-c8fe-4872-9c75-946cc00b29a6.us-west-1.linodelke.net:443
  name: lke48818

users:
- name: lke48818-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InAyZ2tPcjZ4aXMyZU1ZcmhZbEVzTko1RWk3aFNxSk5XUTc5elVscUNrZzAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcTJtd20iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWE5OWIyOTMtMzNlYi00MjQ3LWJkMzktNTQyMjVkM2JlZjA4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.FozGypS6XXPyiFSV7EjxGuzY4jyLh29hKQgTWyn3leXaHw0crZakU6Nz6XNYMZgUVr8abbh4ZI3sphlb-sof6qOih5tl07KwBv_fCcmxqNM5BrroGRBT1BFjdQWrRU_XVGEw-bjEBAyxSKlutDeoi6J6U47EJJCom4PEHUOOHd0mItLejrqlvIOBIZFY6ZyWWmbPj-tFgHljjyykP7H-gzj2yNSHn7eze7NEJu03SYodOL-bUu2IoWPshNxaC8DdYDGjxl7c9ZgXOW7Juiv3dlmS2sbv3e1oz3OQQtS5ZYgsFJfJ7HiKYH3UF5IU4ZIq5aoAE-0Y63SG2iNUwriNCw

contexts:
- context:
    cluster: lke48818
    namespace: default
    user: lke48818-admin
  name: lke48818-ctx

current-context: lke48818-ctx
